services:
  - type: web
    name: book-store
    env: java
    plan: free
    branch: main
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/bookStore-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_APPLICATION_NAME
        value: bookStore
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/book?createDatabaseIfNotExist=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: kartik
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.MySQLDialect
